import java.util.*;
class Exception2
{
 public static void main(String args[])
  {
   Scanner sc=new Scanner(System.in);
   int a=sc.nextInt();
   int b=sc.nextInt();
   int c;
    try{
     c=a/b;
     System.out.println("Division of two numbers :"+c);
    }
  catch(ArithmeticException e)
  {
  System.out.println("arithmetic exception" +e);
  }
 }
OUTPUT:
C:\Users\LENOVO\Documents>javac Exception2.java

C:\Users\LENOVO\Documents>java Exception2
7
0
arithmetic exceptionjava.lang.ArithmeticException: / by zero

C:\Users\LENOVO\Documents>java Exception2
4
2
Division of two numbers :2